---
title: Getting started with R and RStudio
subtitle: 'This chapter will show you how to install R and RStudio.'
title-block-banner: yes
engine: knitr
filters:
    - webr-teachr
---

# Background

## Why do we want to learn and use R and RStudio

- R and RStudio are powerful tools for creating a statistical analysis
- It is open-sourced and user-friendly
- It provides reproducible code and report
- Easy data cleaning and visualisation

## What is R and RStudio

R is a free software environment for statistical computing and graphics. RStudio is an integrated development environment (IDE) for R. To understand why we might want to use R with RStudio. We will use the analogy from [Modern Dive book](https://moderndive.com/1-getting-started.html#r-rstudio). Think of R as a car's engine, while the RStudio is like a car's dashboard. We use R to run all the computations and RStudio to provide an interface with convenient features and tools.


# R installation

First, install R. The R language is available through the [The Comprehensive R Archive Network](http://cran.r-project.org/) website. In the next sections, we will show how to install R for different operating systems: Windows, MacOS, and Linux. 

## Windows

Steps:

1. Click *"Download R for Windows"*

2. Click *"base"*

3. Click the link at the top of the page. It should say something like *"Download R-4.4.1 for Windows"*, where the numbers would change to the latest version.

4. Run the downloaded executable file.

5. Allow the installer to change your device.

6. Follow the prompt instructions. You do not need to customise the startup.

## MacOS

Steps:

1. Click *"Download R for macOS"*

2. Under the *"Latest release:"*, click the .pkg base on your system architecture. If you are using **Apple silicon (M1 onwards) Macs**, click the *"R-4.41-arm64.pkg"*, **otherwise**, click the *"R-4.4.1-x86_64.pkg"*.

3. After finishing downloading the .pkg, double-click on it.

4. Follow the installer's instructions. It will involve reading through some documents and clicking continue or install.

5. Once the installation is complete, click *"Close"* to exit the installation process.

## Linux

Steps:

1. Click *"Download R for Linux"*.

2. Click on the directory based on the Linux version you have.

3. Follow the instructions on the website.

# RStudio installation

The RStudio can be downloaded from the [Posit](https://posit.co/download/rstudio-desktop/) website. Scroll down to *All Installers and Tarballs* and download the RStudio version for your operating system.

## Windows

Steps:

1. Click the .exe file. It should look similar to *"RSTUDIO-2024.04.2-764.EXE"*. The number will be different based on the latest version.

2. Run the executable file to install RStudio.

3. Allow the installer to make changes on your computer.

4. Follow the prompts.

5. Search for RStudio on your computer and open it. You are now ready to learn R!

## MacOS

Steps:

1. Click the .dmg file. It should look similar to *"RSTUDIO-2024.04.2-764.DMG"*. The number will be different based on the latest version.

2. Drag RStudio.app into the Applications folder. Now you are ready to use R!

## Linux

Steps:

1. Click download the file based on your Linux version.

2. Follow the instructions prompts.