---
title: Getting started with R and IDE (Integrated Development Environment)
subtitle: 'In this chapter, you will learn how to use R and how to use it with common IDEs.'
title-block-banner: yes
engine: knitr
filters:
    - webr-teachr
---

# Background

## Why do we want to learn and use R and IDE

- R and IDE are powerful tools for creating a statistical analysis
- It is open-sourced and user-friendly
- It provides reproducible code and report
- Easy data cleaning and visualization

## What is R and IDE

R is a free software environment for statistical computing and graphics. IDE, or Integrated Development Environment, is a tool to help you be more productive. The common IDE used with R is RStudio, but we will also cover VS Code with R.

To understand why we might want to R with IDE, we will use the analogy from [Modern dive book](https://moderndive.com/1-getting-started.html#r-rstudio). Think of R as a car's engine, while the IDE is like a car's dashboard. We use R to run all the computations and IDE to provide an interface with convenient features and tools.